apiVersion: v1
kind: PersistentVolume
metadata:
  name: chicken-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/chicken-db"  # This path exists on the Minikube VM
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chicken-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
