apiVersion: v1
kind: Service
metadata:
  name: chicken-service
spec:
  type: NodePort
  selector:
    app: chicken-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007  # Any port between 30000–32767
