apiVersion: apps/v1
kind: Deployment
metadata:
  name: chicken-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chicken-app
  template:
    metadata:
      labels:
        app: chicken-app
    spec:
      containers:
        - name: chicken-container
          image: 844328287985.dkr.ecr.eu-west-1.amazonaws.com/chicken-app:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: chicken-volume
              mountPath: /app/chickens.db  # mount SQLite file
              subPath: chickens.db
      volumes:
        - name: chicken-volume
          persistentVolumeClaim:
            claimName: chicken-pvc
