apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chicken-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chicken-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chicken
  template:
    metadata:
      labels:
        app: chicken
    spec:
      containers:
        - name: chicken
          image: 844328287985.dkr.ecr.eu-west-1.amazonaws.com/chicken-web:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: chicken-volume
              mountPath: /app/chickens.db  # Change this if needed
      volumes:
        - name: chicken-volume
          persistentVolumeClaim:
            claimName: chicken-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: chicken-service
spec:
  type: LoadBalancer
  selector:
    app: chicken
  ports:
    - port: 80
      targetPort: 5000
